common: &common
  weixin:
    app_id: wx003231764af46e05
    app_secret: 4abf8ce55e27eff7f5b08789258aabc9
  qiniu:
    access_key: 32dSXkGyNecoyZTwRQKnNVeINR9wp0_pQAft0obD
    secret_key: m46ZDTtXAvyvotpAlC9EDJ90b7yYqJpplmE-lIbS

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common