# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67322e71373dd5765e51a4e18fe2d068a8f4fba6728d51668382ac6fabd089fefa3660195a68d68e1134b47a5b697731be920ef6f93fc5d68dcfe0a7e6151e4d

test:
  secret_key_base: 05b6feb5c2f63af7c4e8aa8c0ada185b9c1656bb8bd1698f860397c79be976f85500d40c930881ffd882d5ee18d1fc2c5fd33e64c46b21284776f1cc868717d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
